### ISSUE TITLE
Windows image

### ISSUE THREAD

**Issue by kvalev** [payara/docker-payaraserver-full#10]
Hi, are there any plans to provide a Windows docker image?

**Comment by mikecroft** [comment]
No immediate plans as yet - what is your use case? AFAIK, Docker for Windows can seamlessly switch between a linux and windows environment.

**Comment by kvalev** [comment]
Alright, thanks. I guess it is quite an exotic use case, and anyone in case anyone needs a Windows Docker image, it should be fairly straightforward to create one. You can close the issue if you want.

**Comment by mikecroft** [comment]
Thanks! Native Windows docker images are still pretty new, so we'll see if they pick up enough steam to create a supported one.
