### ISSUE TITLE
Unable to pin at current `latest` version

### ISSUE THREAD

**Issue by pblew** [payara/docker-payaraserver-full#11]
`latest` is currently Payara 4.1.1.171.  There are tags for `164`, `163`, etc, but no tag for `171` so in order to use 171, I have to use the `latest` tag.  This means when 172 is released I will automatically update to it rather than choosing to update in a controlled way.

Would it be possible to also create a tag with the actual version of `latest` (ie. `171`) each time a new `latest` is created?

**Comment by mikecroft** [comment]
Sorry, yes, that is the normal process but was missed this time. Thanks for pointing it out!

**Comment by mikecroft** [comment]
Fixed:
https://hub.docker.com/r/payara/server-full/tags/

I'll be updating all the images for the 171.1 release as well as soon as I can.
