### ISSUE TITLE
Changing asadmin "admin" user not working

### ISSUE THREAD

**Issue by marcelActano** [payara/docker-payaraserver-full#110]
The following line is not valid in dockerfile:
echo "AS_ADMIN_PASSWORD=\nAS_ADMIN_NEWPASSWORD=${ADMIN_PASSWORD}" > /tmp/tmpfile && \
The default password is "admin" and not empty.

It schould be:
echo "AS_ADMIN_PASSWORD=admin\nAS_ADMIN_NEWPASSWORD=${ADMIN_PASSWORD}" >/tmp/tmpfile

**Comment by MattGill98** [comment]
Hi Marcel,

The commands seem to run just fine, do you mean to say that when building locally the `change-admin-password` command doesn't execute successfully?

Kind regards,

Matt

**Comment by marcelActano** [comment]
Hi Matt,

Yes, when the command runs does not change the password because the old one(empty in our command) does not match with the actual one(witch is "admin")

Thanks,
Marcel

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
