### ISSUE TITLE
5.194 docker image contains payara 5.193

### ISSUE THREAD

**Issue by RonaldSpierenburg** [payara/docker-payaraserver-full#114]
The latest and 5.194 docker images are still built with version 5.193

When i look at the current 'latest' docker image for payara:server-full (https://hub.docker.com/layers/payara/server-full/latest/images/sha256-1ed16ced429dbb757c0dbd32ee9e86f98a410b47868455ceb9a5c6c227feb612), it shows 'ARG PAYARA_VERSION=5.193' and it downloaded 'PAYARA_PKG=https://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara/5.193/payara-5.193.zip'.

**Comment by rieckpil** [comment]
I figured out the same, once I pull the `payara/server-full:5.194` image and start the docker container, the following version is displayed in the logs:

```
[#|2019-12-04T04:53:46.345+0000|INFO|Payara 5.193|javax.enterprise.logging|_ThreadID=31;_ThreadName=RunLevelControllerThread-1575435226270;_TimeMillis=1575435226345;_LevelValue=800;_MessageID=NCLS-LOGGING-00009;|
  Running Payara Version: Payara Server  5.193 #badassfish (build 252)|#]
```

**Comment by eduarddrenth** [comment]
Same for me, ```--build-arg PAYARA_VERSION=5.194``` doesn't seem to help either

**Comment by eduarddrenth** [comment]
if I exec in the container and issue java -version I do see azul/zulu-openjdk:8u222 though

**Comment by rieckpil** [comment]
It should be fixed now: https://hub.docker.com/layers/payara/server-full/5.194/images/sha256-e68ab6e2fd31a66d73e5f7695ae997c83be2911a89b57aea77b71e29e23736d0. 

Pulling `payara/server-full:5.194` and running a container with this image now results in the following output:
```
[#|2019-12-09T16:10:41.891+0000|INFO|Payara 5.194|javax.enterprise.logging|_ThreadID=31;_ThreadName=RunLevelControllerThread-1575907841824;_TimeMillis=1575907841891;_LevelValue=800;_MessageID=NCLS-LOGGING-00009;|
  Running Payara Version: Payara Server  5.194 #badassfish (build 327)|#]
```

**Comment by smillidge** [comment]
Yeah we had some build issues
