### ISSUE TITLE
Development moving to main repo

### ISSUE THREAD

**Issue by poikilotherm** [payara/docker-payaraserver-full#123]
Hi folks,

could you please update this repo with an updated README that development now happens in the main repo?

Maybe closing all open issues with a hint how to carry on would also be helpfull to spread the word.
Marking this repo as archived might improve awareness, too.

Thank you!

**Comment by fturizo** [comment]
Thanks for the suggestion, @poikilotherm. We are archiving the repository now, so we'll put a warning to indicate that support of the Docker image has been moved to the main repository
