### ISSUE TITLE
Upload latest Docker image for Payara Server 173 (4.1.2.173) to Docker Hub

### ISSUE THREAD

**Issue by lreimer** [payara/docker-payaraserver-full#17]
Can you please upload the latest Docker image for Payara Server 173 (4.1.2.173) to Docker Hub.
Please also tag the image using the full version `payara/server-full:173`, in addition to `latest`.

**Comment by mikecroft** [comment]
`latest` has been updated, the 173 tag should be done shortly too. `payara/server-web` and `payara/micro` should follow along soon after, they're all queued up in Docker Hub

**Comment by lreimer** [comment]
Thanks for the quick response. All tags are on Docker Hub now. Closing this issue.
