### ISSUE TITLE
asadmin commands against 5-SNAPSNOT doesn't work

### ISSUE THREAD

**Issue by baztian** [payara/docker-payaraserver-full#18]
Having this Dockerfile

    FROM payara/server-full:5-SNAPSHOT
    
    ENV PASSWORD_FILE /opt/pwdfile
    WORKDIR ${PAYARA_PATH}/bin
    RUN ./asadmin start-domain ${PAYARA_DOMAIN} && \
        ./asadmin --user ${ADMIN_USER} --passwordfile ${PASSWORD_FILE} delete-jvm-options -Xmx512m
    
Running `docker build . -t payara-base:5-SNAPSHOT` causes SSLHandshakeException:

    Sending build context to Docker daemon  4.096kB
    Step 1/4 : FROM payara/server-full:5-SNAPSHOT
     ---> 64496a412329
    Step 2/4 : ENV PASSWORD_FILE /opt/pwdfile
     ---> Using cache
     ---> e823f4a228a9
    Step 3/4 : WORKDIR ${PAYARA_PATH}/bin
     ---> 2a1f900aa39c
    Step 4/4 : RUN ./asadmin start-domain ${PAYARA_DOMAIN} &&     ./asadmin --user ${ADMIN_USER} --passwordfile ${PASSWORD_FILE} delete-jvm-options -Xmx512m
     ---> Running in b4198ebb9a78
    Waiting for domain1 to start ...
    Successfully started the domain : domain1
    domain  Location: /opt/payara50/glassfish/domains/domain1
    Log File: /opt/payara50/glassfish/domains/domain1/logs/server.log
    Admin Port: 4848
    Command start-domain executed successfully.
    NCLS-ADMIN-00010
    javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    Command delete-jvm-options failed.
    The command '/bin/sh -c ./asadmin start-domain ${PAYARA_DOMAIN} &&     ./asadmin --user ${ADMIN_USER} --passwordfile ${PASSWORD_FILE} delete-jvm-options -Xmx512m' returned a non-zero code: 1

Version 173 doesn't have this issue.

**Comment by smillidge** [comment]
you need to remove the -Xbootclasspath  for the grizzly-npn jar  from your jvm options in your Payara configuration unless you are on a spceific version of the Oracle JDK.

**Comment by baztian** [comment]
Thanks @smillidge,
be aware that my Dockerfile is based on Payaras official image. It used to work with the 173 version. I think removing the Xbootclasspath is something the docker-payaraserver-full project should provide as a default. Otherwise the Docker image is useless for most serious projects.

If I want to do it by myself: How or where can I change this without building a payara docker image from scratch?

**Comment by smillidge** [comment]
true it's a known issue but it is currently a snapshot version.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
