### ISSUE TITLE
Change Master Password on Payara/Glassfish Server NOT Working

### ISSUE THREAD

**Issue by seanhuni** [payara/docker-payaraserver-full#21]
Background: I need to change the payara-server master-password. According to the docs the master-password must match the password in the keystore & truststore for the SSL Certificates to work properly. To make my website run on https instead of http with a CA certificate
![screen shot 2017-11-21 at 12 06 27 pm](https://user-images.githubusercontent.com/6264211/33068496-3d0362e0-ceba-11e7-9b43-88674dfafd8b.png)
.

I got Payara-Server running in a Docker Container through the guide:

I tried to change the payaradomain master-password, but I get an acyclic error. I made sure the payara-domain isn't running.

`- ./asadmin stop-domain --force=true payaradomain`
When I run this command, instead domain1 gets killed. & then kicked out of the docker container:
`./asadmin stop-domain --kill=true payaradomain`
When I execute this command:

`./asadmin list-domains`
Response:

```
domain1 running
payaradomain not running
Command list-domains executed successfully.
```
Then tried command:

`./asadmin stop-domain --force=true payaradomain`
Response:

` CLI306: Warning - The server located at /opt/payara41/glassfish/domains/payaradomain is not running.`
I'm happy with that, but when I try:

`./asadmin change-master-password payaradomain`
I get this response:

`Domain payaradomain at /opt/payara41/glassfish/domains/payaradomain is running. Stop it first.`

I have attached the [picture in this link](https://i.stack.imgur.com/FkijC.png): please help...

**Comment by mikecroft** [comment]
Looks like the exception message is incorrect. You probably need to stop domain1 or just start the container with an interactive shell rather than starting Payara Server.

**Comment by mikecroft** [comment]
Answered:

https://stackoverflow.com/questions/47411022/change-master-password-on-payara-glassfish-server/47453368#47453368
