### ISSUE TITLE
Upload latest Docker image for Payara Server 174 (4.1.2.174) to Docker Hub

### ISSUE THREAD

**Issue by larslorenzen** [payara/docker-payaraserver-full#22]
Hi,
Can you please upload the Docker image tag for Payara Server 174 (4.1.2.174) to Docker Hub.

Also for the micro payara please :)

**Comment by mikecroft** [comment]
They're all queued up to build now. Should be available in the next few minutes!

Looks like the LATEST tag was updated, but not the explicit 174.

**Comment by larslorenzen** [comment]
Thanks a lot
