### ISSUE TITLE
Gitter for discussion on this project

### ISSUE THREAD

**Issue by johnmanko** [payara/docker-payaraserver-full#26]
I have some questions on how to use this docker image, but it's not appropriate to ask here.  Instead, can you create a `payara` or `payara-docker` Gitter?  Maybe even Slack.

**Comment by mikecroft** [comment]
The best place for discussions on these things are our Payara Forum. We had a lot of people ask for a place for discussion and the consensus was that most people prefer a mailing list format over chat like Gitter or Slack.
https://groups.google.com/forum/#!forum/payara-forum

**Comment by OndrejM** [comment]
Yes, the Payara forum is the best place to ask any questions about Payara Server and related projects, including the Docker images.
