### ISSUE TITLE
starting the container in debug mode?

### ISSUE THREAD

**Issue by rsoika** [payara/docker-payaraserver-full#32]
Is it possible to start the payara in debug mode

I tried to set the environment variable 

` POSTBOOT_COMMANDS: "--debug true"`

But this did not work. Is there a way to enable payara debug?

**Comment by moxim** [comment]
Hi,

the docs at https://github.com/payara/docker-payaraserver-full states:

> It's possible to run a custom set of asadmin commands by specifying the POSTBOOT_COMMANDS environment variable to point to the abslute path of the custom post boot command file. In that case, the default entry point won't deploy applications in /opt/payara41/deployments, you will have to specify the deploy command(s) in your custom post boot command file.

So, it looks like you will have roll your own...

**Comment by rsoika** [comment]
yes - I fixed it with a custom domain.xml file and the entrypoint

`entrypoint: "/opt/payara41/bin/startInForeground.sh --passwordfile=/opt/pwdfile -d --postbootcommandfile glassfish/domains/domain1"`
