### ISSUE TITLE
Optionally generate Let'sEncrypt certificate upon container startup

### ISSUE THREAD

**Issue by OndroMih** [payara/docker-payaraserver-full#38]
If possible, generate Let'sEncrypt certificate when the container is started and when an environment variable is set to TRUE. 

Follow http://www.amihaiemil.com/2017/10/03/letsencrypt-glassfish-ec2.html to configure Let'sEncrypt with Payara.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived. @OndroMih, if this is still something relevant, raise an internal JIRA in the `CUSTCOM` project to track this.
