### ISSUE TITLE
Appending to post-boot-commands.asadmin on every startup

### ISSUE THREAD

**Issue by deltapi** [payara/docker-payaraserver-full#41]
Currently payara5 appends everything in its $DEPLOYMENT_DIR to the post-boot-commands.asadmin on every startup, resulting in multiple successive deployments of the same artifact. 

I think the issue is located in generate_deploy_commands.sh, where in line 26 it is appended instead of overwritten

**Comment by murdos** [comment]
This is indeed problematic, but the behavior of generate_deploy_commands.sh at line 26 is useful, when you want to initialize beforehand the postbootcommandfile with customs commands, either when building the docker image, or when the container starts.

**Comment by deltapi** [comment]
Thanks for your reply. I don't really understand yet how/when the deployment files are written. Nevertheless it would be very nice if you could have a look into the re-adding of commands that are already listed.

**Comment by MattGill98** [comment]
Fixed in https://github.com/payara/docker-payaraserver-full/pull/59.
