### ISSUE TITLE
payara/server-full - no 5.182 tag, just latest

### ISSUE THREAD

**Issue by andyfcdl** [payara/docker-payaraserver-full#44]
We like to use explicit versions in our downstream docker files, which we have been doing for 5.181, but there appears to be no explicit version tag for 5.182 in Docker hub - just latest.

Are there plans to tag it with the version number?

**Comment by OndrejM** [comment]
Hi, definitely! Just sometimes too many things are happenning and this part isn't automated enough to make sure that docker images are released at the same time with binaries. But we're trying to be at least eventually consistent ;-)

**Comment by OndrejM** [comment]
The 5.182 is released now.
