### ISSUE TITLE
security: tags not updated

### ISSUE THREAD

**Issue by shoeper** [payara/docker-payaraserver-full#50]
According to https://hub.docker.com/r/payara/server-full/tags/ tags are not updated. The issue is that security updates from the base image are not included in your images.

To solve this issue you have to rebuild each tag whenever openjdk:8-jdk was updated (which itself depends on debian:stretch and is rebuild when that one is updated).

**Comment by shoeper** [comment]
docker-payaramicro and docker-payaraserver-web suffer from the same issue.

**Comment by shoeper** [comment]
See also https://quay.io/repository/shoeper/test?tab=tags

payara-server-full-5.182 is the current image from docker hub. payara ist the same image build today. With older images there are more vulnerabilities.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
