### ISSUE TITLE
image is bloated

### ISSUE THREAD

**Issue by shoeper** [payara/docker-payaraserver-full#51]
The image is bloated with temporary files.

Each RUN command creates a new layer, which means when you download a file an delete it in a separate layer it will not be visible but still be downloaded on docker pull and still is going to occupy space on the server.

To solve the issue you need to e.g. fetch an artifact, install and delete it within the same layer. Same with apt, do not leave the cache in a layer. Run update install and if only temporarily needed also remove within the same RUN command and do not forget to remove the apt cache as well (rm -rf /var/lib/apt/lists/*).

**Comment by shoeper** [comment]
docker-payaramicro and docker-payaraserver-web are also affected.

**Comment by smillidge** [comment]
do you want to make a PR?

**Comment by shoeper** [comment]
No, do not plan to make one.

**Comment by smillidge** [comment]
Any reason why not?

**Comment by shoeper** [comment]
Sorry, any reason why I should? I don't use payara, but saw the two issues while I came by and thought it could be helpful to report them.

On your website it looks like there is official support for the docker images... I wonder about them not getting security updates and about their size.

**Comment by smillidge** [comment]
Fair enough if you don't use Payara. Thank you for your advice and guidance.

**Comment by shoeper** [comment]
So, I've tried to improve this and got rid of about one third of its compressed size (compare payara and payara2 at https://quay.io/repository/shoeper/test?tab=tags).

But, I also found out that there are more issues. The admin password stuff does not work very well, as we can see with `docker run --rm -it -p4848:4848  payara/server-full:4.181` which outputs
```
/opt/pwdfile: line 2: EOF: command not found
```

Also when removing `--passwordfile=/opt/pwdfile` from the entrypoint which should work according to the entrypoint script payara fails to run.

And there are more issues
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
```
https://stackoverflow.com/a/22509753/5923915

```
D=51;_ThreadName=Thread-14;_TimeMillis=1535894890579;_LevelValue=1000;_MessageID=NCLS-SECURITY-05054;|
  The SSL certificate has expired: [
[
  Version: V3
  Subject: OU=Equifax Secure Certificate Authority, O=Equifax, C=US
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5
```

```
[#|2018-09-02T13:28:10.823+0000|INFO|Payara 4.1||_ThreadID=1;_ThreadName=main;_TimeMillis=1535894890823;_LevelValue=800;|
  PlainTextActionReporterFAILUREFile not found : /opt/payara41/deployments/*|#]
```

```
[#|2018-09-02T13:28:10.914+0000|INFO|Payara 4.1||_ThreadID=13;_ThreadName=FelixStartLevel;_TimeMillis=1535894890914;_LevelValue=800;|
  /opt/payara41/glassfish/domains/domain1/autodeploy/bundles does not exist, please create it.|#]
```

And all files are changed to be owned by payara. I'm sure if that's needed and from a security perspective it would be better to have only write permissions where it is required.
