### ISSUE TITLE
Generate admin console certificate on first run

### ISSUE THREAD

**Issue by shoeper** [payara/docker-payaraserver-full#52]
Currently all users get the same - public - ssl certificate for the admin console. It would be better if everyone would get a generated one on first run.

**Comment by OndrejM** [comment]
I don't think that anything should be generated on a first run. All should be configured during build. The stock docker image is just for development. For production, everybody should extend it and customize, ideally recreate production domain during the build which also generates a new SSL certificate. We can add a script to help with that during build time.

**Comment by shoeper** [comment]
> For production, everybody should extend it and customize, ideally recreate production domain during the build which also generates a new SSL certificate.

I'm not sure what the advantage is to let everyone wanting to use it do the same work. I think it would be better if the image would directly would have as many tweaks if possible.

If there is too much overhead for a development image it could be worth creating two images, one for development and one for production if as many tweaks as possible added. On the other hand that would possibly lead to errors in production not found in development because different environments are being used.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
