### ISSUE TITLE
asadmin command not found

### ISSUE THREAD

**Issue by shoeper** [payara/docker-payaraserver-full#55]
At least with payara/server-full:latest@sha256:9ba625667910d775a40e47100730a320cbf59e0f2732e39c1262e3ebd74e9f18 asadmin is not on path and it's required to first navigate to /opt/payara5/bin

**Comment by OndrejM** [comment]
This was never the case. The Dockerfile uses `${PAYARA_PATH}/bin/asadmin` to execute asadmin. But we can add it to the path.

**Comment by OndrejM** [comment]
If you want to contribute, you can send a pull request to do it.
