### ISSUE TITLE
remove the payara package file

### ISSUE THREAD

**Issue by thomas-mc-work** [payara/docker-payaraserver-full#6]
Removing the payara package file will save you ~122 MB in the image:

    RUN rm $PKG_FILE_NAME

**Comment by mikecroft** [comment]
Thanks for the suggestion! You're quite right, I've created `PYSVC-185` to make that change here and in `docker-payaraserver-web`

**Comment by mikecroft** [comment]
Change made in `full` and `web`. Currently building to Docker Hub under the LATEST tag.
