### ISSUE TITLE
Why is 5-SNAPSHOT docker tag not using the current payara snapshot build?

### ISSUE THREAD

**Issue by pioneer2k** [payara/docker-payaraserver-full#62]
The Dockerfile is downloading an old payara prerelease from 
https://s3-eu-west-1.amazonaws.com/payara.fish/payara-5-prerelease.zip
wich was last modified back in august.
The current prerelease can be found under https://s3-eu-west-1.amazonaws.com/payara.fish/payara-prerelease.zip

My expectation for a SNAPSHOT-Docker-Image is that it uses the current snapshot build of payara,

**Comment by OndrejM** [comment]
We're fixing the nighly docker tag. The `5-SNAPSHOT` tag will be deprecated, instead we'll use the `prerelease` tag for nightly builds of an upcoming version.

There's already a PR for this here:  #60

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
