### ISSUE TITLE
startInForeground.sh compatibility enhancement idea

### ISSUE THREAD

**Issue by phillipross** [payara/docker-payaraserver-full#63]
While customizing the payara-server-full docker image to run on alpine linux with azul's java8u192, I found that the startInForeground.sh script did not run since the alpine image does not install bash.  Rather than modifying the image to install bash, I changed the following line which works both for both the debian and alpine images:
```
--- a/java/payara/payara-server-full/startInForeground.sh
+++ b/java/payara/payara-server-full/startInForeground.sh
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env sh
 ##########################################################################################################
 #
 # This script is to execute Payara Server in foreground, mainly in a docker environment.
```

**Comment by phillipross** [comment]
Well, this appears not to work completely with the latest revised startInForeground.sh script which uses source to load the password file as it's apparently bash-specific.  Installing the bash package in alpine is probably the best route to take to maintain compatibility/maintainability 🤔

**Comment by poikilotherm** [comment]
Maybe this can be changed to? Haven't tested it, but maybe a "sh" instead of "." will be fine in terms of running the init scripts?

**Comment by phillipross** [comment]
I'll try it and report back

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
