### ISSUE TITLE
Proposal: make production domain ready for application scoped resources by default

### ISSUE THREAD

**Issue by poikilotherm** [payara/docker-payaraserver-full#65]
Dear devs,

@smillidge pointed out in payara/Payara#3449 (THX!!!) that you need to set the JVM option `-Ddeployment.resource.validation=false` to be able to create application scoped resources for JMS and others.

IMHO it is most likely that users of this image will conduct their resources in these ways instead of adding asadmin scripts for domain config. Setting the JVM option via Preboot has no effect, you need it inside the domain config *before* the JVM is started.

I propose to add another change to the Dockerfile that includes this option by default.

Please comment :-)
(Willing to create a PR including code and docs if you give this a go-ahead)

Cheers,
Oliver

**Comment by OndrejM** [comment]
How do you set the system property? Did you try using the asadmin command `create-system-properties` in a post boot command file?
The system property is evaluated during each deployment, it isn't cached, so it should work.

**Comment by poikilotherm** [comment]
I use the PREBOOT_COMMANDS option, [see my script](https://github.com/poikilotherm/dataverse/blob/9d1f2ce657892d9130220abbc1711629931e7e66/conf/docker/app/init_2_configure.sh)

The options get created, but they are only useable after a domain restart.

**Comment by poikilotherm** [comment]
Thanks @OndrejM, when using the POSTBOOT_COMMANDS, this works smoothly.
Is this an upstream bug?

**Comment by poikilotherm** [comment]
@johnmanko: Beware, this is NOT working as expected. At some places in Payara docs there is mentioned that with preboot scripts only `set` commands work, other tell "not all commands work". I still don't know if this is a bug or not. I expected that adding the properties before anything is booted would be correct. At least this could (should?) be clarified in the docs...

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
