### ISSUE TITLE
Proposal: Create ENV Variable to allow passing of asadmin commands directly

### ISSUE THREAD

**Issue by colangelo-david** [payara/docker-payaraserver-full#68]
I have run into this on at least two projects now and it seems people are interested in a quick way to run the container in debug mode as mentioned [here](https://github.com/payara/docker-payaraserver-full/issues/32) and[ here](https://github.com/payara/docker-payaraserver-full/issues/16) however that currently prevents you from taking advantage of the auto deploys built into the container code currently as [noted in the docs](https://github.com/payara/docker-payaraserver-full) and the [linked issue](https://github.com/payara/docker-payaraserver-full/issues/32).  The proposal is to add an environment variable `ADMIN_COMMANDS` that can be overridden to allow passing of arguments to the `startInForeground.sh` script to be run with the asadmin command.  

I have tested the changes already and the seem to work nicely with the following changes  

`Dockerfile`

```
ENV HOME_DIR=/opt/payara\
    PAYARA_DIR=/opt/payara/appserver\
    SCRIPT_DIR=/opt/payara/scripts\
    CONFIG_DIR=/opt/payara/config\
    DEPLOY_DIR=/opt/payara/deployments\
    PASSWORD_FILE=/opt/payara/passwordFile\
    # Payara Server Domain options
    DOMAIN_NAME=production\
    ADMIN_USER=admin\
    ADMIN_PASSWORD=admin \
    ADMIN_COMMANDS=\
    # Utility environment variables
    JVM_ARGS=\
    DEPLOY_PROPS=\
    POSTBOOT_COMMANDS=/opt/payara/config/post-boot-commands.asadmin\
    PREBOOT_COMMANDS=/opt/payara/config/pre-boot-commands.asadmin

```

`startInForeground.sh`
```
...

OUTPUT=`${PAYARA_DIR}/bin/asadmin --user=${ADMIN_USER} --passwordfile=${PASSWORD_FILE} start-domain --dry-run --prebootcommandfile=${PREBOOT_COMMANDS} --postbootcommandfile=${POSTBOOT_COMMANDS} $ADMIN_COMMANDS $@ $DOMAIN_NAME`

....
```

Which allows you to create a Dockerfile as follows: 

```
FROM payara/server-full:5.183

ENV ADMIN_COMMANDS --debug

COPY webapp.war $DEPLOY_DIR
```
which will run the app in debug mode and allow connections on 9009

**Comment by AllenConquest** [comment]
@colangelo-david, I only just saw your post. I put forward a pull request (https://github.com/payara/docker-payaraserver-full/pull/77) to do just that and it was accepted, so you can now use the PAYARA_ARGS environmental variable to do things like setting debug on. In fact that is why I made this change myself, and thought others might find it useful.

**Comment by colangelo-david** [comment]
@AllenConquest You the man! my local change looks identical I guess i should have just Submitted it as a PR. On any note thanks again!
