### ISSUE TITLE
What is the idiomatic way to deploy a driver through mountpoints, outside the war?

### ISSUE THREAD

**Issue by ninrod** [payara/docker-payaraserver-full#69]
Hi, I'm trying to __[assemble](https://github.com/ninrod/kotlin-angular-payara)__ a build where I can have a payara server full configured to access a database. postgresql, for instance.

Deploying a single war is easy enough. I just mount the war to the deployment directory.

Now say that I want to use a mountpoint to also teach payara about the postgresql driver. how can I do that? 

At first I thought that setting up a `lib/` directory sided with the war would work. But it does not. 

As a user, I'd like to say to payara: Here's my war, and here are all the jars you need to load in order to work with this war.

Is there a way to do that with the payara docker image?

**Comment by poikilotherm** [comment]
As tested for IQSS/dataverse, Payara is happy to have the driver inside the WAR when deploying JDBC resources from either `@DataSourceDefinition` or placed like `glassfish-resources.xml`.

Maybe this helps avoiding some headaches?

**Comment by ninrod** [comment]
I would like to place the jars outside of the war. I'd rather to have a thin war because there will be 50 deployments per day and I'd like to optimize network and storage usage. 

So the main idea would be to have a base image with all the jars that my war needs and a 50kb layer on top of it with only the thin war. 

Is that possible?

**Comment by colangelo-david** [comment]
Yes, if you know what JAR's you need you can manually drop it in the payara install by copying it over from your local machine while building the image. I used to do this for my JDBC jar on Payara 4. The Docker file had a command that was effectively 

```
COPY db-connector-java.jar ${PAYARA_PATH}/glassfish/modules/db-connector-java.jar
```

Then in your pom.xml you need to set it to `<provided>` so your pom.xml will look like this. 

```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>db-connector-java</artifactId>
            <version>0.0.0</version>
            <scope>provided</scope>
</dependency>
```

**Comment by poikilotherm** [comment]
You can also copy it to `${PAYARA_DIR}/glassfish/domains/${DOMAIN}/lib`.

Please be aware that not every JAR can be put there. Things like OmniFaces and others *require* to be within the WAR, as specified by Servlet 3.0 spec. (That hit me when I was aiming for a thin WAR...)

**Comment by ninrod** [comment]
allright, thanks for the responses. just leaving this open so that we can have an opportunity of a getting a reply by a core developer.

**Comment by MattGill98** [comment]
Hi @ninrod,

Firstly thank you to everyone who commented on this issue, it's great seeing such engagement! Everything said so far is perfectly accurate. I believe that the most idiomatic way to provide these JARs is typically through the WAR's `WEB-INF/lib` directory. If this is not possible as you suggested, I would recommend putting these JARs into the `DOMAIN_DIR/lib` directory (thanks @poikilotherm ). This makes the classes accessible to every deployed application. Below are a couple of ways of doing this:

### Option 1

Create your own image built from the Payara Server image. In your Dockerfile you can add the JARs required into the `${PAYARA_DIR}/glassfish/domains/production/lib` directory (thanks @colangelo-david).

### Option 2

Mount this directory at runtime using [docker's volume mounting](https://docs.docker.com/storage/volumes/). For example, the following command would start the Payara Server docker image with the JARs found in `/opt/jars` automatically loaded to the `lib/` directory of your domain:

~~~
docker run --rm --name payara -v /opt/jars/:/opt/payara/appserver/glassfish/domains/production/lib/ payara/server-full:5.184
~~~

I hope this helps.

Kind regards,

Matt

**Comment by phillipross** [comment]
> You can also copy it to `${PAYARA_DIR}/glassfish/domains/${DOMAIN}/lib`.
> 
> Please be aware that not every JAR can be put in those places. Things like OmniFaces and others _require_ to be within the WAR, as specified by Servlet 3.0 spec. (That hit me when I was aiming for a thin WAR...)

@poikilotherm in the case of omnifaces outside the war, i'm not familiar with the part of the spec that might explicitly state the jar needs to be bundled inside the war (does the spec hate thin wars?) but to get things working, tweaking the classloader delegation settings via a deployment descriptor can sometimes fix the problem.  I think the mechanics of this are covered in the payara server documentation.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
