### ISSUE TITLE
What's the purpose of $PAYARA_PATH/deployments?

### ISSUE THREAD

**Issue by thomas-mc-work** [payara/docker-payaraserver-full#7]
What's the purpose of [Line 18](https://github.com/payara/docker-payaraserver-full/blob/master/Dockerfile#L18) in the Dockerfile?

    RUN mkdir -p $PAYARA_PATH/deployments

**Comment by mikecroft** [comment]
It's a known location for you to use in scripts. There's nothing special about it, other than it makes life a bit easier to write "`asadmin deploy $PAYARA_PATH/deployments/$MYAPP`" rather than writing out a long path. Just a convenience.

**Comment by thomas-mc-work** [comment]
Ok. Would be nice to have a mention in the [deployment section of the README](https://github.com/payara/docker-payaraserver-full#application-deployment).
