### ISSUE TITLE
Update to JDK 1.8u192 due to backports for container support OOB and security

### ISSUE THREAD

**Issue by poikilotherm** [payara/docker-payaraserver-full#70]
With [JDK-8146115](https://bugs.openjdk.java.net/browse/JDK-8146115) being backported to 1.8u191 (see also docker-library/openjdk#245), I would really like to see the image updated to v1.8u192 to include the latest sec fixes, too.

I am happy to create a PR that changes the version and updates the `RUN`...
@MattGill98, @smillidge and @OndrejM any thoughts on this what might stop us? Eventually disable HTTP2 as a workaround for 5.183 grizzly npn issue #56?

**Comment by phillipross** [comment]
I'd like to put forth the suggestion of basing the docker image off of azul's zulu openjdk docker images.  They provide images for multiple distributions (centos, debian, ubuntu, and alpine),  provide the source for how those images are built, offer commercial support to those who need it, plus it seems to align with payara's commercial support offerings partnering with azul.  I'm not sure what the downsides would be.

**Comment by poikilotherm** [comment]
@MattGill98 @Pandrex247 @OndrejM do you want me to create a PR for this update? Happy to stay on 1.8.191, too. If you feel uncomfortable with Azul, maybe we could provide it as a separate Docker tag for interested parties?

**Comment by poikilotherm** [comment]
I just took a dive into this... This seems to be blocked by docker-library/openjdk#245 as long as we don't want Zulu. 

I tried Zulu and it definitly needs adoption in the Dockerfile as they use a different base image for their Ubuntu/Debian flavors compared to OpenJDK official image.

Feedback is appreciated.

**Comment by AllenConquest** [comment]
Is there any reason why the full payara docker image isn't built from the same one as micro payara? I have my own custom images based on openjdk:8-jdk-alpine and it works fine. I may have tinkered with the startup scripts a bit to ensure they worked in alpine's shell, but other than that it's great. The images are much smaller, and it has the latest backports used by java (so I'm using better memory management)

**Comment by MattGill98** [comment]
Hi @poikilotherm and @AllenConquest,

I see no problems with using Azul and Alpine. From memory the only reason it isn't currently using that is the Dockerfile depends on some libraries that are easier to obtain on Ubuntu. By all means create a PR and we'll be happy to review it!

Kind regards,

Matt

**Comment by AllenConquest** [comment]
@MattGill98 would it be possible to create another tag like some other distributions. Something like 5.191-alpine so people have an option as to which image to use? My current testing of a new aphine image has it coming in at under 300MB!

**Comment by OndroMih** [comment]
Right now, we can only support one base image and we have to decide which one. Until now, it's been OpenJDK based on Ubuntu. It seems that this combination isn't supported anymore and OpenJDK now supports Debian (Slim) and Alpine based images: https://github.com/docker-library/openjdk/tree/b8ce9eff38451de3282b2eb2bcd8b520fb95e1ce/8/jdk

Looking at Zulu images, Azul provides Ubuntu-based and Alpine-based images.

For some reason, the size of the openjdk:8u171-jdk image, which is now the base for Payara Server images, is way too big: 624 MB. Azul's Ubuntu-based image is only 337MB.

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
openjdk                    8u201-alpine        88d1c219f815        6 days ago          105MB
openjdk                    8u212-slim          e2581abdea18        12 days ago         243MB
azul/zulu-openjdk-alpine   8u202-8.36.0.3      cf664c55b9ab        8 weeks ago         213MB
azul/zulu-openjdk          8u202-8.36.0.1      de147fea5810        8 weeks ago         337MB
openjdk                    8u171-jdk           8c80ddf988c8        8 months ago        624MB
```

I think that switching to Azul's Ubuntu-based images is currently the safest option, reducing the size of Payara Server image by 300 MB. If we later decide to support also Alpine variant or switch to it from Ubuntu, then we could either use OpenJDK or Azul Alpine image.

**Comment by smillidge** [comment]
I would switch to the Azul Alpine image like Payara Micro

**Comment by phillipross** [comment]
I've been using azul's alpine image since 8u192 and have had zero problems.  With the release of 5.192 I've switched to azul's 11.0.3 on alpine and it's working great so far.

**Comment by poikilotherm** [comment]
I guess this can be closed, as we are on Azul 8u222 now. :wink:
