### ISSUE TITLE
Payara 5.184: 100% CPU from GFFileHandler

### ISSUE THREAD

**Issue by pioneer2k** [payara/docker-payaraserver-full#72]
With the new Payara 5.184 Docker Image we get a 100% CPU utilization from GFFileHandler Thread. 
Even if we start the Docker Image without any deployment.
This seems to be caused by this setting in the logging.properties file:
com.sun.enterprise.server.logging.GFFileHandler.logtoFile=false
Nothing is written to the server.log and the CPU utilization goes to 100%.

If I change the property to true the logs are written to the server.log and the CPU utilization goes back to normal.

**Comment by poikilotherm** [comment]
This seems to be the case since 92e6c65dca4d65806bb128f33e0123193bb6536d and is related to my upstream bug report https://github.com/payara/Payara/issues/3506.

Good to see this is present in latest Payara, too and I am not alone. :+1:

**Comment by OndrejM** [comment]
I confirm this. I also saw that just starting Payara Server 5.184 official docker image, without any deployments, will drive CPU to the top. It doesn't happen with 5.183 (on both domain1 and production domains), but happens when the dataverse app is deployed as described in https://github.com/payara/Payara/issues/3506

**Comment by StefanSchubert** [comment]
Hi, I could confirm this behavior with 5.183 and 5.184 on centOS.

**Comment by MattGill98** [comment]
Hi @pioneer2k,

This has been fixed in the 5.184 tag by https://github.com/payara/docker-payaraserver-full/pull/74. An upstream issue has been made which is linked above. I'll close this issue, although feel free to reopen it if you find the issue reoccurs!

Cheers,

Matt
