### ISSUE TITLE
Problem while creating a data grid with Payara

### ISSUE THREAD

**Issue by theirman** [payara/docker-payaraserver-full#76]
Hello, 

I would like to create a data grid with Payara to increase availability of my web applications. Only, I've been struggling for 4 days trying to figure out how to create a data grid under Payara. I am a beginner on Payara and, even if I have a short experience with Glassfish3, I have never had to manage either cluster or data grid, only a standalone machine.

I created 3 machines as shown below:

    [admin@centos7 payara-production]$ docker ps -a
    CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                                                                              NAMES
    d838b911cd9e        sicpa/payara:production   "/tini -- scripts/en…"   About an hour ago   Up About an hour    9009/tcp, 0.0.0.0:4850->4848/tcp, 0.0.0.0:4902->4900/tcp, 0.0.0.0:5902->5900/tcp, 0.0.0.0:8082->8080/tcp, 0.0.0.0:8183->8181/tcp   vigilant_hermann
    90829218f754        sicpa/payara:production   "/tini -- scripts/en…"   About an hour ago   Up About an hour    9009/tcp, 0.0.0.0:4849->4848/tcp, 0.0.0.0:4901->4900/tcp, 0.0.0.0:5901->5900/tcp, 0.0.0.0:8081->8080/tcp, 0.0.0.0:8182->8181/tcp   optimistic_dewdney
    0e47c13b2855        sicpa/payara:production   "/tini -- scripts/en…"   About an hour ago   Up About an hour    0.0.0.0:4848->4848/tcp, 0.0.0.0:4900->4900/tcp, 0.0.0.0:5900->5900/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8181->8181/tcp, 9009/tcp   thirsty_stallman

Each of its machines uses a domain called **production**

Theoretically, the *thirsty_stallman* machine should be my DAS (Domain Admin Service) and the other two, *optimistic_dewdney* and *vigilant_hermann*, should be members of the data grid.

But that's not the case, and I don't know why. It seems that each of my machines behaves like DAS and waits for instances to join them:

+ **thirsty_stallman** *(port forwarding: 4848->4848, 8080->8080, 8181->8181, 4900->4900, 5900->5900)* : screenshot [here](https://www.developpez.net/forums/attachments/p447448d1549359899/java/plateformes-java-ee-jakarta-ee-spring-serveurs/serveurs-d-applications/glassfish-payara/creer-data-grid-sous-payara-glassfish/02.png/)

+ **optimistic_dewdney** *(port forwarding: 4848->4849, 8080->8081, 8181->8182, 4900->4901, 5900->5901)* : screenshot [here](https://www.developpez.net/forums/attachments/p447451d1549359991/java/plateformes-java-ee-jakarta-ee-spring-serveurs/serveurs-d-applications/glassfish-payara/creer-data-grid-sous-payara-glassfish/03.png/)

+ **vigilant_hermann** *(port forwarding: 4848->4850, 8080->8082, 8181->8183, 4900->4902, 5900->5902)* : screenshot [here](https://www.developpez.net/forums/attachments/p447453d1549360029/java/plateformes-java-ee-jakarta-ee-spring-serveurs/serveurs-d-applications/glassfish-payara/creer-data-grid-sous-payara-glassfish/04.png/)

Before asking, I read a lot of documentation including [this](https://blog.payara.fish/domain-data-grid-in-payara-server-5) and [this](https://docs.payara.fish/documentation/payara-server/hazelcast/enable-hazelcast.html) but none of it has helped me to progress so far.

My questions:

+ How to create a single DAS, in a unique way?
+ How to link other servers to the DAS?
+ How to launch the data grid? manage the data grid?
+ How to deploy SOAP or REST applications in the data grid?

Any ideas ?
Thanks

**Comment by MattGill98** [comment]
Hi @theirman,

GitHub issues are best for issues with the code itself. Since this is a question of usage, I would recommend raising the question on our forum: https://groups.google.com/forum/#!forum/payara-forum. The reason for this is to help promote a discussion around it for others to find.

Briefly WRT your question, I would recommend reviewing the cluster methods [described in our documentation](https://docs.payara.fish/documentation/payara-micro/clustering/autoclustering.html), particularly the DNS and TCP/IP discovery methods! We intend to release a guide soon on Payara Platform usage within Docker containers, which may help you with your usage.

I'll close this issue, although please do continue the discussion on our forum, I imagine this will be useful for many others!

Cheers,

Matt

**Comment by theirman** [comment]
Thanks @MattGill98 ,
I will therefore restart this discussion on the Payara forum and I will look at your link about automatic clustering
