### ISSUE TITLE
Use ${SCRIPT_DIR} in CMD

### ISSUE THREAD

**Issue by eduarddrenth** [payara/docker-payaraserver-full#82]
The Dockerfile now reads:

```
ENTRYPOINT ["/tini", "--"]
CMD ["scripts/entrypoint.sh"]
```
when changed to
```
ENTRYPOINT ["/tini", "--"]
CMD ${SCRIPT_DIR}/entrypoint.sh
```
it is more generic and better overridable

**Comment by AllenConquest** [comment]
@eduarddrenth seems sensible to use the variable, as that is where the scripts are copied to.
