### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by AllenConquest** [payara/docker-payaraserver-full#83]
Would it be useful to update the README.md to show that the container timezone can be set by passing in a TZ environment variable? For example `docker run --env TZ=Europe/London payara/docker-payaraserver-full`

**Comment by OndroMih** [comment]
Is that really the case? Where does the support for the TZ variable come from? From bash or from the system? There's nothing special in the Dockerfile to support it.

**Comment by AllenConquest** [comment]
@OndroMih Yes, I found using alpine I had to include the tzdata package to get the functionality, but when I tried it on the master image it worked fine. It is documented in plenty of places on the internet (e.g https://medium.com/@ibrahimgunduz34/be-careful-while-playing-docker-about-timezone-configuration-e7a2217e9b76)

**Comment by AllenConquest** [comment]
In my alpine image I'm setting the default to Europe/London, but you can override that if needed.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
