### ISSUE TITLE
POSTBOOT_COMMANDS create-javamail-resource commandCannot find fromAddress

### ISSUE THREAD

**Issue by mhauschild** [payara/docker-payaraserver-full#87]
Hi,

I'm trying to set my domain.xml via POSTBOOT_COMMANDS which I have created once through the asadmin recorder.

I get an command like:
Running command: create-javamail-resource --mailhost=myhost --mailuser=myuser mail --auth=false --fromaddress=do-not-reply@domain.de --storeprotocol=imap --storeprotocolclass=com.sun.mail.imap.IMAPStore --transprotocol=smtp --transprotocolclass=com.sun.mail.smtp.SMTPTransport --enabled=true --debug=false --target=domain

Followed by the Error Message:
PlainTextActionReporterFAILUREorg.jvnet.hk2.config.UnsatisfiedDependencyException: injection failed on org.glassfish.resources.javamail.admin.cli.CreateJavaMailResource.fromAddress with class java.lang.StringDescription: create-javamail-resource commandCannot find fromAddress in create-javamail-resource command model, file a bug 
Usage: create-javamail-resource --mailhost=mailhost --mailuser=mailuser [--password=password] [--auth=false] --fromaddress=fromaddress [--storeprotocol=imap] [
--storeprotocolclass=com.sun.mail.imap.IMAPStore] [--transprotocol=smtp] [--transprotocolclass=com.sun.mail.smtp.SMTPTransport] [--enabled=true] [--debug=false] [--property=property] [--target=server] [--description=description] jndi_name

Does anybody has an idea?

I also tried to copy my fully configured domain.xml in Dockerfile via:
COPY ./domain.xml $PAYARA_DIR/glassfish/domains/$PAYARA_DOMAIN/config/domain.xml

This does not work. Follows this Blog article: https://ralph.blog.imixs.com/2018/03/01/running-payara-and-postgresql-in-docker/

Thanks a lot for any hints.

**Comment by mhauschild** [comment]
Could do a workaround inspired by: https://github.com/payara/Payara/issues/3005
1.) removed --description
2.) moved bold jndi_name --mailuser=mailuser **mail** to the end of the command

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
