### ISSUE TITLE
Possible RaceCondition during startup in docker version payara5.193 ?

### ISSUE THREAD

**Issue by StefanSchubert** [payara/docker-payaraserver-full#97]
Hi,

for evaluation I switched a project from 5.183 to 5.193 but now the autodeployment/bootstrapping phase aborts from time to time with the following error.

From time to time, means it might not occur if i just stop the container and restart it.
I also experienced that I can influence this behavior by (in/de)creasing the available CPUs to the docker daemon.

`[#|2019-09-24T20:14:47.931+0200|SEVERE|Payara 5.193|javax.enterprise.system.core|_ThreadID=1;_ThreadName=main;_TimeMillis=1569348887931;_LevelValue=1000;|
  Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type HttpServletResponse with qualifiers @Context
  at injection point [UnbackedAnnotatedField] @Inject @Context private fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response
  at fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response(RolesPermittedInterceptor.java:0)
 -- WELD-001408: Unsatisfied dependencies for type HttpServletResponse with qualifiers @Context
  at injection point [UnbackedAnnotatedField] @Inject @Context private fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response
  at fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response(RolesPermittedInterceptor.java:0)
|#]

[#|2019-09-24T20:14:47.966+0200|WARNING|Payara 5.193|fish.payara.boot.runtime.BootCommand|_ThreadID=1;_ThreadName=main;_TimeMillis=1569348887966;_LevelValue=900;|
  Boot Command deploy failed PlainTextActionReporterFAILUREDescription: deploy AdminCommandError occurred during deployment: Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type HttpServletResponse with qualifiers @Context
  at injection point [UnbackedAnnotatedField] @Inject @Context private fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response
  at fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response(RolesPermittedInterceptor.java:0)
 -- WELD-001408: Unsatisfied dependencies for type HttpServletResponse with qualifiers @Context
  at injection point [UnbackedAnnotatedField] @Inject @Context private fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response
  at fish.payara.appserver.cdi.auth.roles.RolesPermittedInterceptor.response(RolesPermittedInterceptor.java:0)
. Please see server.log for more details.
    [name=IdGeneratorProto
 |#]`

Cheers
Stefan

**Comment by OndroMih** [comment]
Hi @StefanSchubert, we need to get a reproducer to be able to fix this reliably. From the logs, it seems that the error comes from the `RolesPermittedInterceptor`. In 5.193, there's a change in that interceptor that relies on injection of HTTP request and response objects. These come from the JAX-RS container and it's possible that the interceptor is sometimes triggered sooner than the container is available.

I assume that your app uses `@fish.payara.cdi.auth.roles.RolesPermitted` somewhere in your application. Can you try to reproduce the same behavior with a very simple application using `@RolesPermitted` and describe how you run the container, especially how you configure the available CPUs to raise the probability it happens? Do you always use `@RolesPermitted` within the JAX-RS context, e.g. in JAX-RS resources, or also somewhere else where the JAX-RS context (request, response) isn't available?

**Comment by StefanSchubert** [comment]
Hi @OndroMih ,

I have inherited the app as maintenance engineer, and just did a full text search for 'RolesPermitted'
which doesn't find a single hit. Sorry ;-)

For the CPU increasement, I was refering to my local development environment, where I am using docker desktop (community edition, docker version 19.03.2) on my Mac. There in the preference settings I'm able to tell the demon how many CPUs it can use.

The target environment for the container is kubernetes and I doubt that the effect would come up there, since the POD will start with "128m" CPU which is 1/8 core in my settings. The limit is set to 4 CPUs but in bootstrapping it will be surely so slow, that the race-condition doesn't occur. 

Hope it helps.

BTW: I like the new directory layout of the 5.193 and the dismissal of the domain1 profile. However setting the timezone seems to have changed.

Cheers
Stefan

**Comment by StefanSchubert** [comment]
According mentioned timezone issue, it was cased due to the switch of the base image. The hint in #83 solved the issue for me. I needed to change the install of tzdata.

I vote that tzdata will be part of the payara image, as I guess that quite a lot of people require to place their backend in the proper timezone.
