### ISSUE TITLE
Tuning config for kubernetes environment?

### ISSUE THREAD

**Issue by StefanSchubert** [payara/docker-payaraserver-full#98]
Hi,

I'm not sure if all k8s environments doing it the same way. But on the sites I know the TLS termination happens on the Ingress. 

Meaning, for those cases we do not require default certificates or TLS Listener with the default payara bundle (and getting rid of ugly SEVERE console messages when they expire). 

How about disable them by default or providing an environment flag which does the trick? 
This may speed up the bootstraping and spare a few resources.

Cheers
Stefan

**Comment by OndroMih** [comment]
This is already possible if you specify the following command in the post boot command file referenced by the PREBOOT_COMMANDS variable:

```
set configs.config.server-config.network-config.network-listeners.network-listener.http-listener-2.enabled=false
```

Obviously, for that you either need to modify the pre boot command file and thus create a custom docker image, or provide the file in a mounted volume.

If you want to configure this with a simple env var, you can put the following command into your custom docker image's pre boot command file:

```
set configs.config.server-config.network-config.network-listeners.network-listener.http-listener-2.enabled=${ENV=HTTPS_ENABLED}
```

Then you can specify the value true or false for the HTTPS_ENABLED var and Payara Server will enable/disable the HTTPS listener according to it when the container is started.

We'll consider supporting the environment variable in the stock Docker image.

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
