### ISSUE TITLE
jdk11

### ISSUE THREAD

**Issue by terrywpf** [payara/docker-payaraserver-full#99]
Hope to release the jdk11 version of the mirror soon

**Comment by alexander-dammeier** [comment]
I would be very happy if an official image for java11 were published.
So the community can also report bugs and test whether their applications also run under Payara-Java11.

**Comment by rieckpil** [comment]
any progress on this?

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived and this will be internally tracked in JIRA.
